code review 1
JohnPush/HomeTaskReactRedux pull request #1
Opened 2024-01-14 10:53 UTC by JohnPush

2024-01-15 16:55 UTC, Levitinn requested changes

2024-01-15 16:55 UTC, Levitinn commented on src/App.jsx
> +	const arrayFilms = [
когда используешь моки, стоит вынести его за пределы компонента. в твоем случае arrayFilms будет каждый раз пересоздаваться при обновлении App, и повлечет за собой ререндер всех дочерних компонентов

2024-01-15 16:55 UTC, Levitinn commented on src/layouts/Header/Header.jsx
непонятное решение. по сути, компонент хедер только рендерит навбар, добавляя к нему обертку с классом хедер. в таком случае, лучше, наверно реализовать навбар внутри хедера, а от самого навбара избавиться

2024-01-15 16:55 UTC, Levitinn commented on src/layouts/Body/Body.jsx
аналогично с навбаром, компонент боди вообще не несет никакой смысловой логики.  удали его, и вытащи всех чилдренов в апп

2024-01-15 16:55 UTC, Levitinn commented on src/components/Heading/Heading.jsx
внутри хединга у тебя поиск, вероятно стоит переименовать компонент в search

2024-01-15 16:55 UTC, Levitinn commented on src/components/Paragraph/Paragraph.jsx
так же не несет никакой логики.  просто рендерит хардкод текст.

2024-01-15 16:55 UTC, Levitinn commented on src/components/ListFilm/ListFilm.jsx
> +function ListFilm({ children }) {
лучше передавать внутрь не чилдренов, а сам список. И мапить его здесь, внутри компонента. А ты вытащил наружу компонента его логику, а именно - рендер списка

2024-01-15 16:55 UTC, Levitinn commented on src/App.jsx
> +							<RatingButton valueRating={el.valueRating} />
зачем передаешь его чилдреном если внутри, ты этот компонент  рендеришь?

2024-01-15 16:55 UTC, Levitinn commented on src/components/RatingButton/RatingButton.jsx
> +	console.log('valueRating:', valueRating);
лишние консоли нужно убирать перед МР

2024-01-15 17:16 UTC, JohnPush commented on src/App.jsx
> +	const arrayFilms = [
понял. буду исправлять

2024-01-22 17:58 UTC, Levitinn requested changes

2024-01-22 17:58 UTC, Levitinn commented on src/App.jsx
> +				/>
текст относится к поиску и инпут относится к поиску, это явно один компонент, а у тебя он поделен на два.
вынеси их логику в один компонент Search

2024-01-22 17:58 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
нет проверки на то что arrayFilms пустой, нужно сделать

2024-01-22 17:58 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
> +				<button
здесь должен быть один компонент Rating, без обертки в button. полагаю что button должна быть внутри рейтинга

2024-01-22 17:58 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
> +					<div>{el.nameFilm}</div>
либо в мапе сделать проверку что имя фильма есть. либо `<div>{el.nameFilm || ''}</div>`

2024-01-22 17:58 UTC, Levitinn commented on src/components/FavoriteButton/FavoriteButton.jsx
> +function FavoriteButton({ onClick }) {
onCLick принимается, но не передается в компонент. лишний пропс?

2024-01-22 17:58 UTC, Levitinn commented on src/components/FavoriteButton/FavoriteButton.jsx
> +	const handleButtonClick = (e) => {
полагаю, так лучше
`
const handleButtonClick = (e) => {
                 if (!onclick) return;
		e.stopPropagation();
		setIsFavorite(!isFavorite);
		onClick();
	};`

2024-01-22 17:58 UTC, Levitinn commented on src/components/InputForm/InputForm.jsx
> +		<div className="input-form_search" onSubmit={addCardFilm}>
onSubmit атрибут формы, зачем он тут?

2024-01-22 17:58 UTC, Levitinn commented on src/components/RatingButton/RatingButton.jsx
> +		<button className="rating-button" onClick={handleButtonClick}>
сделай див, у дивов нет проблем со стилями. а button имеет ограничения, Что усложняет стилизацию

2024-02-13 15:08 UTC, Levitinn requested changes

2024-02-13 15:08 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
не исправлено

2024-02-13 15:08 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
> +				<div key={el.id} className={styles['card-button']}>
сделай чтобы этот мап возвращал компонент карточка фильма, и вся верстка и логика карточки пусть будет в нем

2024-02-14 13:31 UTC, Levitinn commented
- окно регистрации\входа, не должно быть на главной странице, а должно выводиться только на своем урле отдельном.
- вся логика, относящаяся к авторизации, должна быть в отдельном компоненте отвечающем за авторизацию
-

2024-02-14 13:39 UTC, Levitinn requested changes

2024-02-14 13:39 UTC, Levitinn commented on src/App.jsx
> +	const onSubmit = (values) => {
этот обработчик тоже не имеет отношения к компоненту апп, и должен быть внутри search

2024-02-14 13:39 UTC, Levitinn commented on src/components/NavBar/NavBar.jsx
> +	const handleLogout = () => {
этот обработчик, так же, не относится к Навбару, и должен быть в авторизации

2024-02-14 13:39 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
> +	if (arrayFilms.length === 0) {
if (!arrayFilms.length) return компонент заглушка показывающий что фильмов нет. 
иначе высота страницы будет скакать из за того что компонент то есть, то нет. и в этмо примере лучше делать это не вначале компонента, а в верстке проверять если дата есть, то рендерить карточки, если нет - рендерить текст "фильмов нет"

2024-02-17 10:15 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
> +			{arrayFilms.length > 0 ? (
!!arrayFilms.length  ? ..... : .....

2024-02-17 10:15 UTC, Levitinn commented on src/components/NavBar/NavBar.jsx
> +	const handleLogout = () => {
не исправлено

2024-02-17 10:16 UTC, Levitinn commented on src/App.jsx
> +	const onSubmit = (values) => {
не исправлено

2024-02-17 10:19 UTC, Levitinn requested changes

2024-02-17 10:19 UTC, Levitinn commented on src/App.jsx
> +					<Login onSubmit={addUser} />
думаю, корректно будет не отображать окно входа если пользователь уже залогинен

2024-02-17 12:47 UTC, JohnPush commented on src/components/ListFilms/ListFilms.jsx
> +			{arrayFilms.length > 0 ? (
"!!" вызывает ошибку
Redundant double negation.eslint[no-extra-boolean-cast](https://eslint.org/docs/latest/rules/no-extra-boolean-cast)
(parameter) arrayFilms: any


можно ли убрать "!!" и оставить только arrayFilms.length ? ..... : .....    ?

2024-02-17 19:06 UTC, Levitinn commented on src/components/ListFilms/ListFilms.jsx
> +			{arrayFilms.length > 0 ? (
есЛинт все правильно говорит. в случае с тернарником !! не нужны, достаточно arrayFilms.length ? (.....)

2024-02-17 19:08 UTC, Levitinn commented on src/App.jsx
> +					<Login onSubmit={addUser} />
будет правильнее, если ты сделаешь отдельный компонент Auth в котором будет и handleLogout, и рендер войти\выйти при соответствующем стейте. так ты очистишь навбар от ненужного стейта авторизации

2024-02-20 20:13 UTC, Levitinn commented
вроде все хорошо, но мне тут пришло в голову, что не логично показывать кнопки в избранное если пользователь не авторизован. Думаю будет правильно их не отображать до авторизации, так как в них нет смысла. в этом МР можешь не исправлять, это просто идея к проработке наперед

2024-02-20 20:13 UTC, Levitinn approved these changes

2024-02-21 12:50 UTC, merged