2 style
JohnPush/HomeTaskReactRedux pull request #2
Opened 2024-02-22 19:15 UTC by JohnPush

1. сделал хук локал сторадж
2. не понял как сделать контекст

3. удалил хук локал сторадж
4. сделал контекст, но он не корректно работает не понимаю как исправить

2024-02-24 11:58 UTC, Levitinn requested changes

2024-02-24 11:58 UTC, Levitinn commented on src/App.jsx
>  	const loggedInUserName = loggedInUser ? loggedInUser.userName : '';
нужно использовать стейт. реакт не следит за значениями переменных, потому компонент не будет обновляться при их изменении.

2024-03-04 18:52 UTC, Levitinn requested changes

2024-03-04 18:52 UTC, Levitinn commented on src/context/user.context.jsx
> +	const getCurrentUser = () => {
ты занес эти две переменные в контекст. Смотри, сейчас у тебя все корректно отрабатывает, при изменении users (loggedInUser корректно пробрасывается в Auth и рендерит компонент) но есть ряд случаев, когда эта реактивность потеряется, иными словами, этот код потенциальная уязвимость. Стоит использовать useState для обоих переменных внутри getCurrentUser

2024-03-04 18:52 UTC, Levitinn commented on src/components/NavBar/NavBar.jsx
>  					<div className={styles['menu__counter']}>X</div>
что значит "Х" ? 
![image](https://github.com/JohnPush/HomeTaskReactRedux/assets/44999446/47e573ed-4676-40f6-afc1-7b8a805246d7)

2024-03-04 18:52 UTC, Levitinn commented on src/App.jsx
> +					<ListFilms arrayFilms={arrayFilms} />
почему ты передаешь пустой массив? фильмы же не отображаются. Расскомменчивай перед отправкой мр массив

2024-03-04 18:56 UTC, JohnPush commented on src/components/NavBar/NavBar.jsx
>  					<div className={styles['menu__counter']}>X</div>
заглушка. До тех пока не начнем добавлять кино в избранное. Давай по порядку. Пока делаем только то есть в ДЗ.
На последнем КР будем добивать все что можно

2024-03-05 18:04 UTC, JohnPush commented on src/App.jsx
> +					<ListFilms arrayFilms={arrayFilms} />
На ноуте надо будет тогда листать чтобы добраться до формы авторизации.

2024-03-05 19:43 UTC, Levitinn approved these changes

2024-03-05 19:43 UTC, Levitinn commented on src/context/user.context.jsx
> +		if (user) {
`
setLoggedInUser(user || null);
setLoggedInUserName(user?.userName || '');
`
 можно вообще убрать условие и прописывать вот так. как вариант

2024-03-05 20:04 UTC, merged